name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  env:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: config
      run: |
          chmod -R 777 *
          git config core.filemode false

  build:

    runs-on: ubuntu-latest
    steps:

    - name: Build with Gradle
      run: ./gradlew build
