name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Prepare config
        shell: bash
        continue-on-error: true
        run: |
          chmod -R 777 *
          git config core.filemode false

      # - name: Gradle Build 
      #   shell: bash
      #   continue-on-error: true
      #   run: |
      #     ./gradlew build

      - name: veridex_check
        shell: bash
        continue-on-error: true
        run: |
          ### export PATH
          export PATH=$PATH:${ANDROID_HOME}/emulator:${ANDROID_HOME}/platform-tools:${ANDROID_HOME}/tools:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/build-tools/30.0.3:${ANDROID_HOME}/build-tools/30.0.3/lld-bin:${ANDROID_HOME}/ndk/23.0.7599858
          ./gradlew :dev-sdk:build
          echo "veridex_check 测试结果 ">./veridex_check.txt
          
          if [ $# == 0 ]; then
            # wget https://github.com/hhhaiai/tools/releases/download/v1.0/appcompat.tar.gz
            tar zxvf ./appcompat.tar.gz
            echo "===================tar zxvf appcompat.tar.gz结果 ">>./veridex_check.txt
            ls -la>>./veridex_check.txt
            tree>>./veridex_check.txt
            cp appcompat/veridex-linux.zip ./veridex-linux.zip
            unzip veridex-linux.zip
            echo "=======unzip veridex-linux.zip">>./veridex_check.txt
            ls -la>>./veridex_check.txt
            tree>>./veridex_check.txt
          fi
          
        #  if [ $# == 0 ]; then
        #       fi
         
          
          # cp ./dev-sdk-debug.aar ./veridex/
          # echo "cp ./dev-sdk-debug.aar ./veridex/ " >>./veridex_check.txt
          # ls>>./veridex_check.txt
          # cd veridex
          # echo "cd veridex " >>./veridex_check.txt
          # ls>>./veridex_check.txt
          # chmod -R 777 *
          # unzip dev-sdk-debug.aar
          # echo "unzip dev-sdk-debug.aar" >>./veridex_check.txt
          # ls>>./veridex_check.txt
          # chmod -R 777 *
          # echo "解压dev-sdk-debug方法，测试dx">>./veridex_check.txt
          # ${ANDROID_HOME}/build-tools/30.0.3/dx >>./veridex_check.txt
          # echo "解压aar完毕，即将DX转换。。。。">>./veridex_check.txt
          # ${ANDROID_HOME}/build-tools/30.0.3/dx --dex --output=target.dex classes.jar
          # echo "DX转换完成。。。。">>./veridex_check.txt
          # ls -la>>./veridex_check.txt
          # ./appcompat.sh --dex-file=target.dex>>./veridex_check.txt

      - name: Upload veridex_check
        if: success()
        continue-on-error: true
        uses: actions/upload-artifact@v1
        with:
          name: veridex_check.txt
          path: ./veridex_check.txt
